camel case handling
devonfw/jump-the-queue pull request #103
Opened 2021-11-17 11:02 UTC by dixyushi

2021-11-24 14:54 UTC, ssarmokadam requested changes

2021-11-24 14:54 UTC, ssarmokadam commented on .spellcheck.yml
> +        close: '[^-]*'
Change it to latest regex. 
```
 - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      # Ignore multiline content between [source, *] and blank line
      - open: '\[source,.*\]\r?\n\s*----'
        close: '\s*----'
```

2021-11-24 14:54 UTC, ssarmokadam commented on documentation/build-devon4j-application.asciidoc
> +Press "Shift + Right Click" and select "Open Devon `CMD` shell here". +
cmd should not be in backtick... it is in dict check and remove backtick

2021-11-24 14:54 UTC, ssarmokadam commented on documentation/build-devon4j-application.asciidoc
> +Be sure that you are using devonfw `CMD` or bash, as the command is not working properly with devonfw `PowerShell`.
cmd and powershell in dict

2021-11-24 14:54 UTC, ssarmokadam commented on documentation/build-devon4j-application.asciidoc
> +** _api_ project for the common `API`
api -> dict

2021-11-24 14:54 UTC, ssarmokadam commented on documentation/devon4j-adding-custom-functionality.asciidoc
> +=== Creating the usecasemanage for the `AccessCode`
remove backtick from heading and divide word as Access Code

2021-11-24 14:54 UTC, ssarmokadam commented on documentation/devon4j-adding-custom-functionality.asciidoc
> +==== Adding method to the `AccessCode` _usecasefind_
same as above

2021-11-24 14:54 UTC, ssarmokadam commented on documentation/devon4j-adding-custom-functionality.asciidoc
> +To add the new service, we need to add its definition to the `jtqj-api` in `accesscodemanagement/service/api/rest/AccesscodemanagementRestService.java`. We are going to create a new `/accessCode` `RE
REST-> dict

2021-11-24 14:54 UTC, ssarmokadam commented on documentation/devon4j-adding-custom-functionality.asciidoc
> +//TODO: This fails due to an `SQL` Error: 23506
SQL->dict

2021-11-24 14:54 UTC, ssarmokadam commented on documentation/devon4j-adding-custom-functionality.asciidoc
> +To test the delete, you can send a *DELETE* to this `URL`:
URL->dict

2021-11-24 14:54 UTC, ssarmokadam commented on documentation/devon4j-components.asciidoc
> +* _Service_ layer: exposes the `REST` API to exchange information with client applications
REST->dict

2021-11-24 14:54 UTC, ssarmokadam commented on documentation/devon4j-components.asciidoc
> +.An entity and its corresponding table in the `DB` (taken from another application).
DB to dict

2021-11-24 14:54 UTC, ssarmokadam commented on documentation/devon4j-components.asciidoc
> +Finally we are going to provide a certain amount of mock data, which will be available right from the start in our application. Create a new `SQL` script in `/jtqj-core/src/main/resources/db/migratio
SQL->dict

2021-11-24 14:54 UTC, ssarmokadam commented on documentation/devon4j-components.asciidoc
> +We are going to use `CobiGen` to generate the component structure. That means that -- as already commented -- we can generate all the structure and layers starting from a _core_ element: a simple _Pl
CobiGen->dict

2021-11-24 14:54 UTC, ssarmokadam commented on documentation/devon4j-components.asciidoc
> +The contents of _QueueEntity_ before using `CobiGen` will be:
CobiGen->dict

2021-11-24 14:54 UTC, ssarmokadam commented on documentation/devon4j-components.asciidoc
> +Now we can resolve the compilation errors related to `QueueEntity` in the `AccessCodeEntity.java` by applying the suggestions of the `IDE`. To do this, open the offending file, click the first red li
IDE->dict

2021-11-24 14:54 UTC, ssarmokadam commented on documentation/devon4j-components.asciidoc
> +=== The Component Structure (using `CobiGen`)
same as above

2021-11-24 14:54 UTC, ssarmokadam commented on documentation/devon4j-components.asciidoc
> +* _CRUD `SpringData` Repository_: Generates the entity repository (that contains the `CRUD` operations) in the data access layer.
CRUD->dict

2021-11-24 14:54 UTC, ssarmokadam commented on documentation/devon4j-components.asciidoc
> +image::images/devon4j/4.Components/cobigen5_manual_import.png[`CobiGen` Manual Import]
change all above like previous comments

2021-11-24 14:54 UTC, ssarmokadam commented on documentation/devonfw-intro.asciidoc
> +- _Eclipse_: pre-configured and fully functional `IDE` to develop Java based apps.
same as above

2021-11-24 14:54 UTC, ssarmokadam commented on documentation/devonfw-intro.asciidoc
> +image::images/devon/cobigen.png[`CobiGen`]
remove backticks

2021-11-24 14:54 UTC, ssarmokadam commented on documentation/devonfw-intro.asciidoc
> +*Next Chapter*: link:devonfw-ide-setup.asciidoc[devonfw `IDE` Setup]
remove backticks

2021-11-24 22:48 UTC, dixyushi commented on .spellcheck.yml
> +        close: '[^-]*'
Updated the code

2021-12-02 07:47 UTC, ssarmokadam commented
@suprishi will take over this PR. He will work on review comments and raise new PR. Merging this basic changes.

2021-12-02 07:47 UTC, merged