Fix documentation
devonfw/jump-the-queue pull request #62
Opened 2020-10-15 07:37 UTC by monicalopezgris

2020-10-19 06:52 UTC, sjimenez77 requested changes
Hi @monicalopezgris, I have posted a few comments to improve this PR.

2020-10-19 06:52 UTC, sjimenez77 commented on documentation/devon4ng-adding-custom-functionality.asciidoc
> +        pageable.sort= [];
There is no space between `pageable.sort=`

2020-10-19 06:52 UTC, sjimenez77 commented on documentation/devon4ng-adding-custom-functionality.asciidoc
> +    content: any;
Why not do we create a type in order not to use the `any` type? In general it is a bad practice.

2020-10-19 06:52 UTC, sjimenez77 commented on documentation/devon4ng-adding-custom-functionality.asciidoc
> +    content: any;
Same here regarding `any` type.

2020-11-16 10:58 UTC, mperezor19 commented on angular/src/app/shared/backendModels/interfaces.ts
> +  [x: string]: any;
Is not possible to create an specific type?

2020-11-16 11:10 UTC, mperezor19 reviewed
Check comment

2020-11-16 23:13 UTC, monicalopezgris commented
Created new request

2020-11-17 14:55 UTC, merged